# Generated by Django 4.2.7 on 2024-01-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='author ismi')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='loyiha nomi')),
                ('image', models.ImageField(upload_to='user_info/', verbose_name='loyiha rasmi')),
                ('project_info', models.TextField(verbose_name='qisqacha tafsiloti')),
                ('hashteg', models.CharField(max_length=255, verbose_name='post hashtegi')),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author', verbose_name='author ismi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='kategoriyasi nomi')),
            ],
        ),
    ]
